<?php
/**
 * Responsible for rendering the short codes.
 *
 * @package    wp2fa
 * @subpackage short-codes
 * @copyright  2026 Melapress
 * @license    https://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link       https://wordpress.org/plugins/wp-2fa/
 */

declare(strict_types=1);

namespace WP2FA\Shortcodes;

defined( 'ABSPATH' ) || exit;

use WP2FA\WP2FA;
use WP2FA\Admin\User_Notices;
use WP2FA\Admin\Wizard_Integration;

if ( ! class_exists( '\WP2FA\Shortcodes\Shortcodes' ) ) {
	/**
	 * Class for rendering shortcodes.
	 */
	class Shortcodes {

		/**
		 * Constructor.
		 */
		public static function init() {
			\add_shortcode( 'wp-2fa-setup-form', array( __CLASS__, 'user_setup_2fa_form' ) );
			\add_shortcode( 'wp-2fa-setup-notice', array( __CLASS__, 'user_setup_2fa_notice' ) );

			\add_filter( 'the_content', array( __CLASS__, 'maybe_hide_generated_by_text' ) );
		}

		/**
		 * Strips the "Page generated by WP 2FA Plugin" attribution text from the
		 * custom frontend 2FA page when the hide_page_generated_by setting is enabled.
		 *
		 * @param string $content The post content.
		 *
		 * @return string
		 *
		 * @since 2.8.0
		 */
		public static function maybe_hide_generated_by_text( $content ) {
			if ( ! \is_page() ) {
				return $content;
			}

			if ( ! \has_shortcode( $content, 'wp-2fa-setup-form' ) ) {
				return $content;
			}

			if ( ! WP2FA::get_wp2fa_white_label_setting( 'hide_page_generated_by' ) ) {
				return $content;
			}

			// Remove the attribution paragraph that was embedded in the page content at creation time.
			$content = \preg_replace(
				'#<p>\s*' . \preg_quote( \esc_html__( 'Page generated by', 'wp-2fa' ), '#' ) . '\s*<a [^>]*>.*?</a>\s*</p>#s',
				'',
				$content
			);

			return $content;
		}

		/**
		 * Output setup form.
		 *
		 * @param array $atts - Array with the attributes passed to shortcode.
		 *
		 * @return string
		 */
		public static function user_setup_2fa_form( $atts ) {
			$atts = \shortcode_atts(
				array(
					'show_preamble'       => 'true',
					'redirect_after'      => '',
					'do_not_show_enabled' => 'false',
				),
				$atts
			);

			$show_preamble       = filter_var( $atts['show_preamble'], FILTER_VALIDATE_BOOLEAN );
			$redirect_after      = self::resolve_redirect_after( (string) $atts['redirect_after'] );
			$do_not_show_enabled = filter_var( $atts['do_not_show_enabled'], FILTER_VALIDATE_BOOLEAN );

			/**
			 * Fires when the FE shortcode scripts are registered.
			 *
			 * @param bool $shortcodes - True if called from the short codes method.
			 *
			 * @since 2.2.0
			 */
			\do_action( WP_2FA_PREFIX . 'shortcode_scripts', true );

			if ( \is_user_logged_in() ) {

				$additional_args = array(
					'is_shortcode'   => true,
					'show_preamble'  => $show_preamble,
					'redirect_after' => $redirect_after,
					'options'        => array(
						'do_not_show_enabled' => $do_not_show_enabled,
					),
				);

				$user = \wp_get_current_user();

				ob_start();
				echo self::get_notification_style(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
				echo '<div class="wp-2fa-shortcode-wrapper">';
				User_Notices::user_setup_2fa_nag( 'output_shortcode' );
				Wizard_Integration::render_profile_section_frontend( $user, $additional_args );
				echo '</div>';
				$content = ob_get_contents();
				ob_end_clean();

				return $content;
			} elseif ( ! \is_admin() && ! \is_user_logged_in() ) {
				ob_start();
				$new_page_id = WP2FA::get_wp2fa_setting( 'custom-user-page-id' );
				$redirect_to = ! empty( $new_page_id ) ? \get_permalink( $new_page_id ) : \get_home_url();
				$link_markup = '<a href="' . \esc_url( \wp_login_url( $redirect_to ) ) . '">' . \esc_html__( 'Login here.', 'wp-2fa' ) . '</a>';
				$message     = '<p id="wp_2fa_login_to_view_text">' . str_replace( '{login_url}', $link_markup, WP2FA::get_wp2fa_white_label_setting( 'login-to-view-area', true ) ) . '</p>';
				echo \wp_kses_post( $message );
				$content = ob_get_contents();
				ob_end_clean();
				return $content;
			}
		}

		/**
		 * Turns the redirect_after attribute into a URL on this site.
		 *
		 * The attribute is a path on the site, like the policy redirect setting
		 * ("my-account" for {site url}/my-account); a full URL is accepted too.
		 * Anyone who can write a post can use the shortcode, so a destination off
		 * the site, or with a scheme other than http(s), is dropped.
		 *
		 * @param string $value - The attribute as written in the shortcode.
		 *
		 * @return string The URL to send the user to after setup, or '' for none.
		 *
		 * @since 4.2.0
		 */
		public static function resolve_redirect_after( string $value ): string {
			$value = \trim( \sanitize_text_field( $value ) );
			if ( '' === $value ) {
				return '';
			}

			$is_url    = 0 === \strpos( $value, '//' ) || 1 === \preg_match( '#^[a-z][a-z0-9+.\-]*:#i', $value );
			$candidate = $is_url ? $value : \trailingslashit( \get_site_url() ) . \ltrim( $value, '/' );
			$candidate = \esc_url_raw( $candidate, array( 'http', 'https' ) );
			if ( '' === $candidate ) {
				return '';
			}

			return (string) \wp_validate_redirect( $candidate, '' );
		}

		/**
		 * Output setup nag.
		 *
		 * @param array $atts - Array with the attributes passed to shortcode.
		 *
		 * @return string
		 */
		public static function user_setup_2fa_notice( $atts ) {
			$atts = \shortcode_atts(
				array(
					'configure_2fa_url' => '',
				),
				$atts
			);

			$configure_2fa_url = \esc_url_raw( $atts['configure_2fa_url'] );

			// TODO: is that really necessary?
			User_Notices::init();

			if ( ! is_admin() && is_user_logged_in() ) {
				ob_start();
				User_Notices::user_setup_2fa_nag( 'output_shortcode', $configure_2fa_url );
				$nag = ob_get_contents();
				ob_end_clean();

				if ( '' === \trim( (string) $nag ) ) {
					return '';
				}

				// The nag carries its own script; it only needs the same look as in the setup form.
				return self::get_notification_style() . '<div class="wp-2fa-shortcode-wrapper">' . $nag . '</div>';
			}

			return '';
		}

		/**
		 * Output the style of the nags on FE pages.
		 *
		 * @return string
		 *
		 * @since 4.0.0
		 */
		public static function get_notification_style(): string {
			$styles = <<<CSS
			<style media="screen">
			.wp-2fa-shortcode-wrapper .wp-2fa-nag, .woocommerce .wp-2fa-nag {
				width: 100%;
				border: 1px solid #eee;
				border-left: 3px solid red;
				padding: 12px 15px;
				margin-bottom: 20px;
				font-size: 13px;
			}
			.wp-2fa-shortcode-wrapper .wp-2fa-nag p, .woocommerce .wp-2fa-nag p {
				margin-bottom: 5px
			}
			.wp-2fa-shortcode-wrapper .wp-2fa-nag br + span, .woocommerce .wp-2fa-nag br + span {
				clear: both;
				display: block;
				margin-top: 10px;
				margin-bottom: 10px;
			}
			.wp-2fa-shortcode-wrapper .wp-2fa-nag a.button, .woocommerce .wp-2fa-nag a.button {
				font-size: 13px;
				padding: 0 !important;
				margin-right: 20px;
				background-color: transparent;
			}
			.wp-2fa-shortcode-wrapper .wp-2fa-nag a.button:visited, .woocommerce .wp-2fa-nag a.button:visited {
				color: #222;
			}
			</style>
			CSS;

			return $styles;
		}
	}
}
